### ISSUE TITLE
UnsatisfiedLinkError: 'long com.sun.javafx.font.freetype.OSPango.g_utf8_strlen(long, long)'

### ISSUE THREAD

**Issue by bernhardkaindl** [chocoearly44/ZapIt#5] opened 2022-09-06 17:42 UTC
```yaml
lsb_release -av
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```
Tried both the Ubuntu jammy packages `openjdk-17-jdk` and `openjdk-18-jre`.

This happens when clicking the "Add" button to add a new connection:
```
java -jar ~/Downloads/zapit-1.1.jar
Sep 06, 2022 7:39:11 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @594c619b'
Exception in thread "JavaFX Application Thread" java.lang.UnsatisfiedLinkError: 'long com.sun.javafx.font.freetype.OSPango.g_utf8_strlen(long, long)'
  at com.sun.javafx.font.freetype.OSPango.g_utf8_strlen(Native Method)
  at com.sun.javafx.font.freetype.PangoGlyphLayout.layout(PangoGlyphLayout.java:143)
  at com.sun.javafx.text.PrismTextLayout.shape(PrismTextLayout.java:849)
  at com.sun.javafx.text.PrismTextLayout.layout(PrismTextLayout.java:1079)
  at com.sun.javafx.text.PrismTextLayout.ensureLayout(PrismTextLayout.java:223)
  at com.sun.javafx.text.PrismTextLayout.getBounds(PrismTextLayout.java:246)
  at javafx.scene.text.Text.getLogicalBounds(Text.java:432)
  at javafx.scene.text.Text.doComputeLayoutBounds(Text.java:1138)
  at javafx.scene.text.Text$1.doComputeLayoutBounds(Text.java:143)
  at com.sun.javafx.scene.shape.TextHelper.computeLayoutBoundsImpl(TextHelper.java:95)
  at com.sun.javafx.scene.NodeHelper.computeLayoutBounds(NodeHelper.java:107)
  at javafx.scene.Node$13.computeBounds(Node.java:3475)
  at javafx.scene.Node$LazyBoundsProperty.get(Node.java:9691)
  at javafx.scene.Node$LazyBoundsProperty.get(Node.java:9661)
  at javafx.scene.Node.getLayoutBounds(Node.java:3490)
  at javafx.scene.control.skin.LabeledSkinBase.layoutLabelInArea(LabeledSkinBase.java:539)
  at javafx.scene.control.skin.LabeledSkinBase.layoutLabelInArea(LabeledSkinBase.java:461)
  at javafx.scene.control.skin.LabeledSkinBase.layoutChildren(LabeledSkinBase.java:445)
  at javafx.scene.control.Control.layoutChildren(Control.java:601)
  at javafx.scene.Parent.layout(Parent.java:1207)
  at javafx.scene.Parent.layout(Parent.java:1214)
  at javafx.scene.Parent.layout(Parent.java:1214)
  at javafx.scene.Parent.layout(Parent.java:1214)
  at javafx.scene.Scene.doLayoutPass(Scene.java:579)
  at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2515)
  at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:421)
  at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
  at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:420)
  at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:450)
  at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:575)
  at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:555)
  at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:548)
  at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:353)
  at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
  at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
  at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
  at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by chocoearly44** [comment] 2022-09-06 19:57
The issue is known and has already been fixed in the development branch. I will merge the branch this weekend.

**Comment by chocoearly44** [comment] 2022-09-11 20:55
Issue fixed

**Closed as completed by chocoearly44** 2022-09-11 20:55 UTC
Labels: bug
